### ISSUE TITLE
"GFE error: Streaming session has failed due to a streaming error. (Error code:521)"

### ISSUE THREAD

**Issue by SireNightFire** [moonlight-stream/moonlight-windows#6]
Yes i pass the requirements on GFE, however it also refuses to work on my iOS device as well
on my PC it just tells me Error code:521

**Comment by mrb113** [comment]
Hi SireNightFire, 
Please report this issue on the iOS page with for now since Moonlight Windows is not ready for the public. 
Also, please provide them there with more information about when you're seeing this issue on your iOS device. 
Thanks,
Michelle
