### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by dimapasko** [moonlight-stream/moonlight-windows#8]
Hi.

Any news about future of this project?

Since Microsoft has just released http://www.microsoft.com/en/mobile/accessory/hd-500/ this project could be a huge thing.

**Comment by mrb113** [comment]
Hi Dima,

The APIs provided by Microsoft are still not sufficient for low latency game streaming - the game is essentially unplayable after just a short period of time with the stream quality we have right now.

I've used that dock, though, and I agree that it would be extra-cool with Moonlight. We will provide updates if anything changes regarding the status of the project.
